Add: CI - フロントエンドのユニットテスト (テストコードは未実装)
Squashed commit of the following:

commit 376b55359703be7ec4b2bddb550e9d6e39e02d19
Author: mugip <strawberry@arisu.cool>
Date:   Fri Jan 29 18:27:02 2021 +0900

    Add: Docker - テスト結果ディレクトリを除外

commit ce31be1b0024253e922f45a85b1a4a7b23df9a90
Author: mugip <strawberry@arisu.cool>
Date:   Fri Jan 29 18:13:05 2021 +0900

    Add: client - JUnit XML によるテスト結果出力, GitHub Checks へのアップロード

commit 74f05de3d2c81fc9aa8bbcb90f06e5114cf92b9b
Author: mugip <strawberry@arisu.cool>
Date:   Fri Jan 29 17:19:21 2021 +0900

    Fix: client - カバレッジ出力先ディレクトリをサーバと一致

commit d860827f52c7af4568aeedf779923a88c4b21b96
Author: mugip <strawberry@arisu.cool>
Date:   Fri Jan 29 17:18:47 2021 +0900

    Change: client - ユニットテストを全く実装していないファイルもカバレッジ集計の対象へ

commit 896d4a60dd9c28a1f98ff45dc0e663ce31cfbc81
Author: mugip <strawberry@arisu.cool>
Date:   Fri Jan 29 16:43:57 2021 +0900

    Fix: client - ユニットテストのカバレッジが Codecov 上で閲覧できない問題

commit 36c20bea0cc3611c43395286c37890ae0fb941f5
Merge: 59377e4 4bba834
Author: mugip <strawberry@arisu.cool>
Date:   Fri Jan 29 04:40:54 2021 +0900

    Merge branch 'master' into ci-unit-test-for-frontend

commit 59377e494b66b5f9e6987eb0d1fdfbb541ab50d0
Author: mugip <strawberry@arisu.cool>
Date:   Fri Jan 29 03:16:41 2021 +0900

    Change: ローカルでのテストを実行しやすく

commit 3717c44ac53c5198a2942f672bdebaa6fd754f98
Author: mugip <strawberry@arisu.cool>
Date:   Fri Jan 29 02:34:19 2021 +0900

    Fix: CI - ブラウザが見つからずにフロントエンドのテストに失敗する問題

commit 38ddbcbfd033eaa7806a7ffce1cfe4f0dead552f
Author: mugip <strawberry@arisu.cool>
Date:   Fri Jan 29 02:31:13 2021 +0900

    Fix: Fix: CI - エラーのときにレポートがアップロードされない問題 (再)

commit eb2129a49e9a399f7e1e6e3eeee9fc25034c9bb2
Author: mugip <strawberry@arisu.cool>
Date:   Fri Jan 29 02:22:36 2021 +0900

    Fix: client - ユニットテストをパスできるようひとまず書き換え・整理

commit 96f49d2060efa89c29a397e9095672799563aad5
Author: mugip <strawberry@arisu.cool>
Date:   Fri Jan 29 02:18:31 2021 +0900

    Fix: ApprovalOnDiscordAction - ビルドエラー

commit a912daa0806c050655094764e27dd5d986c7f27d
Author: mugip <strawberry@arisu.cool>
Date:   Fri Jan 29 02:17:46 2021 +0900

    Add: CI - フロントエンドのユニットテスト (テストコードは未整備)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -68,9 +68,22 @@ jobs:
           if [ -d /tmp/coverage/ ]; then
             mkdir -p /tmp/coverages/server/
             mv /tmp/coverage/* /tmp/coverages/server/
+            rm /tmp/coverage/ -R
+          fi
+          docker cp ${container_id}:/opt/app/packages/client/test-report/result/ /tmp/ || echo "Could not collect server coverage report"
+          if [ -d /tmp/result/ ]; then
+            mkdir -p /tmp/results/client/
+            mv /tmp/result/* /tmp/results/client/
+            rm /tmp/result/ -R
+          fi
+          docker cp ${container_id}:/opt/app/packages/client/test-report/coverage/ /tmp/ || echo "Could not collect server coverage report"
+          if [ -d /tmp/coverage/ ]; then
+            mkdir -p /tmp/coverages/client/
+            mv /tmp/coverage/* /tmp/coverages/client/
+            rm /tmp/coverage/ -R
           fi
 
-      - name: Upload test reports
+      - name: Upload test reports to Artifacts of GitHub Actions
         if: ${{ always() }}
         uses: actions/upload-artifact@v2
         with:
@@ -78,8 +91,19 @@ jobs:
           path: |
             /tmp/npm-test-log.txt
             /tmp/coverages
+            /tmp/results
 
-      - uses: codecov/codecov-action@v1
+      - name: Upload test result of client to GitHub Checks
+        uses: mikepenz/action-junit-report@v2.1.1
+        if: ${{ always() }}
+        with:
+          check_name: Client - Unit Test
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          require_tests: true
+          report_paths: '/tmp/results/client/*.xml'
+
+      - name: 'Upload test coverages to Codecov'
+        uses: codecov/codecov-action@v1
         if: ${{ always() }}
         with:
           directory: /tmp/coverages/
